function StationCHAdeMO_App()
    % Crée la fenêtre principale de l'application
    f = figure('Name', 'Station CHAdeMO', ...
               'Position', [300 100 900 700], ...        % Position et taille [x y largeur hauteur]
               'NumberTitle', 'off', ...                 % Désactive l'affichage du numéro de figure
               'MenuBar', 'none', ...                    % Supprime la barre de menu
               'Resize', 'off', ...                      % Interdiction de redimensionner la fenêtre
               'Color', [0.95 0.95 0.95]);               % Couleur de fond gris clair

    % Affiche un titre principal centré en haut
    uicontrol(f, 'Style', 'text', ...
              'String', '📡 Interface Station CHAdeMO', ...
              'FontSize', 20, ...
              'FontWeight', 'bold', ...
              'FontName', 'Arial', ...
              'BackgroundColor', [0.95 0.95 0.95], ...
              'Position', [250 640 500 40]);

    % Affiche le logo de l'université à gauche du titre
    axesLogo = axes(f, 'Units', 'pixels', 'Position', [30 630 80 50]);
    imshow(imread('téléchargement.jpeg'), 'Parent', axesLogo); % Charge et affiche l'image
    axis off; % Supprime les axes

    % Crée un panneau de contrôle pour les boutons START et STOP
    panelControl = uipanel(f, 'Title', 'Commandes', ...
                           'FontSize', 12, ...
                           'FontWeight', 'bold', ...
                           'BackgroundColor', [0.95 0.95 0.95], ...
                           'Position', [0.35 0.1 0.3 0.15]); % Position en pourcentage (norm.)

    % Bouton START (démarrage de la communication UART)
    uicontrol(panelControl, 'Style', 'pushbutton', ...
              'String', '▶ START', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'Position', [30 30 100 40], ...
              'Callback', @(src, event) envoyerStartUART());

    % Bouton STOP (arrêt de la communication UART)
    uicontrol(panelControl, 'Style', 'pushbutton', ...
              'String', '⏹ STOP', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'Position', [150 30 100 40], ...
              'Callback', @(src, event) envoyerStopUART());

    % Bouton pour quitter l'application proprement
    uicontrol(f, 'Style', 'pushbutton', ...
              'String', 'Quitter', ...
              'FontSize', 12, ...
              'Position', [10, 10, 100, 30], ...
              'Callback', @(src, event) fermetureApp(f));

    % Zone d'affichage de l'image représentant la batterie
    axBattery = axes(f, 'Units', 'pixels', 'Position', [350 310 200 250]);
    imgBattery = imshow(imread('battery_0.png'), 'Parent', axBattery); % Charge image batterie vide
    axis off;

    % Cercle (LED) représentant l'état de charge (couleur variable)
    led = rectangle('Position', [800 620 20 20], ...
                    'Curvature', [1 1], ...              % Forme circulaire
                    'FaceColor', [0.5 0.5 0.5], ...      % Couleur grise par défaut
                    'EdgeColor', 'black');               % Bordure noire

    % Texte statique à côté de la LED
    text(750, 622, 'État :', 'FontSize', 12, 'FontWeight', 'bold');

    % Affiche un message d'état général (texte dynamique)
    txtEtat = uicontrol(f, 'Style', 'text', ...
                        'String', '⏳ En attente...', ...
                        'FontSize', 14, ...
                        'ForegroundColor', [0 0.5 0], ...  % Vert foncé
                        'BackgroundColor', [0.95 0.95 0.95], ...
                        'Position', [300 260 300 30]);

    % Zone d'affichage des valeurs mesurées (tension, courant, SOC)
    txtDonnees = uicontrol(f, 'Style', 'text', ...
                           'String', 'Tension: -- V | Courant: -- A | Batterie: -- %', ...
                           'FontSize', 12, ...
                           'FontName', 'Courier New', ...
                           'Position', [220 220 500 30], ...
                           'BackgroundColor', [0.95 0.95 0.95]);

    % Barre grise représentant la zone de progression SOC
    progressBar = uicontrol(f, 'Style', 'text', ...
                            'Position', [250 180 400 20], ...
                            'BackgroundColor', [0.8 0.8 0.8], ...
                            'HorizontalAlignment', 'left');

    % Barre verte remplie dynamiquement selon le SOC
    fillBar = uicontrol(f, 'Style', 'text', ...
                        'Position', [250 180 0 20], ...      % Largeur 0 au début
                        'BackgroundColor', [0.2 0.7 0.2]);   % Vert

    % Création d'un timer pour lire régulièrement les données UART
    t = timer('ExecutionMode', 'fixedRate', ...              % Exécution périodique
              'Period', 2.0, ...                              % Toutes les 2 secondes
              'TimerFcn', @(~,~) lireDonneesUART( ...
                  txtDonnees, txtEtat, led, imgBattery, fillBar)); % Appel fonction de lecture

    start(t); % Démarre le timer
    setappdata(f, 'timerObject', t); % Enregistre le timer dans les données de l'application

    % Définit la fonction appelée à la fermeture de la fenêtre
    f.CloseRequestFcn = @(src, event) fermetureApp(f);
end

% Fonction de fermeture propre : arrête et supprime le timer, puis ferme la fenêtre
function fermetureApp(fig)
    t = getappdata(fig, 'timerObject'); % Récupère le timer associé
    if isvalid(t)
        stop(t);    % Arrête le timer
        delete(t);  % Supprime le timer
    end
    delete(fig);    % Ferme la figure
end